### ISSUE TITLE
Stretched image in share post as image

### ISSUE THREAD

**Issue by GabrielAstilla** [bricesuazo/cvsu.me#126]
The bug only occurs when the profile pictures are not square ratio. For this example, Bernard's profile size is rectangle. Also, kabsu.me logo is a bit stretched too and change the font to poppins. 

![image](https://github.com/user-attachments/assets/22b9502e-65f4-4252-81c5-2aefe6419819)

**Comment by AlexisKenAlvarez** [comment]
Fixed
https://github.com/bricesuazo/kabsu.me/pull/127
